export const transactions = [
  {
    id: "txn-1001",
    adTitle: "Maths Tuition - Pune",
    template: "Education - Featured",
    placement: "Home + Category Top Slot",
    durationDays: 3,
    baseAmount: 30,
    platformFee: 5,
    gst: 5.4,
    subtotal: 35,
    totalPaid: 40.4,
    paymentMethod: "UPI",
    paymentProvider: "Google Pay",
    paidOn: "2026-03-01",
    status: "Success",
    transactionRef: "UPI-AXIS-893472",
    billedTo: "Atharv Apugade",
    adId: "AD-EDU-22091",
    notes: "Priority placement enabled for 72 hours",
  },
  {
    id: "txn-1002",
    adTitle: "iPhone 14 Pro Sale",
    template: "Electronics - Premium",
    placement: "Search Boost + Category Banner",
    durationDays: 5,
    baseAmount: 90,
    platformFee: 10,
    gst: 18,
    subtotal: 100,
    totalPaid: 118,
    paymentMethod: "Card",
    paymentProvider: "Visa **** 4281",
    paidOn: "2026-02-15",
    status: "Success",
    transactionRef: "CARD-HDFC-112904",
    billedTo: "Atharv Apugade",
    adId: "AD-ELX-88107",
    notes: "Premium card with boosted CTR package",
  },
  {
    id: "txn-1003",
    adTitle: "Dog for Adoption",
    template: "Pets - Basic",
    placement: "Category Listing",
    durationDays: 2,
    baseAmount: 8,
    platformFee: 1,
    gst: 1,
    subtotal: 9,
    totalPaid: 10,
    paymentMethod: "UPI",
    paymentProvider: "PhonePe",
    paidOn: "2026-01-28",
    status: "Success",
    transactionRef: "UPI-ICICI-552908",
    billedTo: "Atharv Apugade",
    adId: "AD-PET-44162",
    notes: "Standard listing package",
  },
];

export function getTransactionById(id) {
  return transactions.find((transaction) => transaction.id === id);
}
